### Api-gateway config
GET http://localhost:9999/config
Content-type: text/plain
Project: My updated super mega  laba 3 for KPI | App: Just simple API-gateway service

### Service (instance 1) config
GET http://localhost:8081/config
Content-type: text/plain
Project: My updated super mega  laba 3 for KPI | App: Just simple mananger API service

### Service (instance 2) config
GET http://localhost:8082/config
Project: My updated super mega  laba 3 for KPI | App: Just simple mananger API service

### Configs in config server
GET http://localhost:8888/application/default
Content-type: application/json

GET http://localhost:8888/feign/default
Content-type: application/json

GET http://localhost:8888/eurekaclientmicroservice/default
Content-type: application/json

### Config refresh
POST http://localhost:8081/actuator/refresh

### FOR API-GATEWAY

### Create entity
POST http://localhost:9999/
Content-type: application/json

{
	"name": "Riko Enriko",
	"age": "22",
	"phone": "+333333437",
	"address": "Faltsova st. 11",
	"clientsCount": "63"
}

### Update entity
PUT http://localhost:9999/1
Content-type: application/json

{
	"name": "Riko Enriko",
	"age": "22",
	"phone": "+4934587",
	"address": "Faltsova st. 11",
	"clientsCount": "403"
}
### Fetch entities
GET http://localhost:9999
Content-type: application/json

### Fetch entity
GET http://localhost:9999/1
Content-type: application/json

### Delete entity
DELETE http://localhost:9999/1